language: go
go:
  - 1.5
  - 1.6
  - tip
install:
  - go get github.com/hashicorp/raft
  - go get github.com/ugorji/go/codec
  - go get github.com/hashicorp/errwrap
  - go get github.com/hashicorp/raft-boltdb
  - go get github.com/stretchr/testify/assert
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken=$COVERALLS_TOKEN || true
script:
  - go test ./...
