language: go
go:
  - 1.5
  - 1.6
  - tip
install:
  - go get github.com/hashicorp/raft
  - go get github.com/ugorji/go/codec
  - go get github.com/hashicorp/errwrap
  - go get github.com/hashicorp/raft-boltdb
  - go get github.com/stretchr/testify/assert
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken=$COVERALLS_TOKEN
script:
  - go test ./...
